### ISSUE TITLE
CSS class gets not removed correctly

### ISSUE THREAD

**Issue by Aybee** [menatwork/semantic_html5#21]
Wrong replacement results in a class name like this:
**wrapper_stopindent_1**
should be
**wrapper_stop indent_1**

https://github.com/menatwork/semantic_html5/blob/1.1.14/system/modules/semantic_html5/SemanticHTML5.php#L82
```js
elem.className = elem.className.replace(" indent ", "");
/* replace above line with this one */
elem.classList.remove("indent");
```

**Comment by davidmaack** [comment]
I won´t fix this, since the indention is broken anyway. Version 2.0.0 uses a correct way to indent the elements.

If anyone still needs this, please provide an PR ;).
