### ISSUE TITLE
Problem with SemanticHTML5Helper::createEndTag

### ISSUE THREAD

**Issue by fritzmg** [menatwork/semantic_html5#22]
I ran into a very specific issue with the `createEndTag` function today. If the `tl_content` DCA has any fields without an `sql` definition, the function will fail. This is because the `createEndTag` function gets the `$objStartTag` as a parameter ([SemanticHTML5Helper.php#L57](https://github.com/menatwork/semantic_html5/blob/409380b173592f2dde4d78d6210277718f66bca4/system/modules/semantic_html5/SemanticHTML5Helper.php#L57)) while this on the other hand is actually the `$dc->activeRecord` ([SemanticHTML5Content.php#L209](https://github.com/menatwork/semantic_html5/blob/409380b173592f2dde4d78d6210277718f66bca4/system/modules/semantic_html5/SemanticHTML5Content.php#L209)). The active record contains every field, _even if it does not have an SQL defintion_ (and thus no corresponding field in the table). However, the `createEndTag` function simply tries to insert every field into the database ([SemanticHTML5Helper.php#L74](https://github.com/menatwork/semantic_html5/blob/409380b173592f2dde4d78d6210277718f66bca4/system/modules/semantic_html5/SemanticHTML5Helper.php#L74)) - which will fail for fields that do not have an `sql` definition of course.

**Comment by davidmaack** [comment]
Do you have an field definition (or an extension using an non-SQL field) where this error occurs? In my 3.5.15 installation only db-fields are presend in the active record...

**Comment by fritzmg** [comment]
It occurred with [fritzmg/contao-be-include-info](https://github.com/fritzmg/contao-be-include-info) in Version `0.5.2` (I temporarily fixed ith in `0.5.3` by adding a dummy SQL definition). You could test with that version (I'll do the same when I have the time).
