### ISSUE TITLE
wrong indentation view in BE

### ISSUE THREAD

**Issue by Aybee** [menatwork/semantic_html5#24]
Version 1.1.14 did not work on Contao 3.5.6. The indentation view is messed up. (FE markup is ok).

Desired example structure:
```
CE

wrapper start
    CE
wrapper end

CE

wrapper start
    CE
wrapper end

CE
```
This picture shows the result
![semantic1 1 14](https://cloud.githubusercontent.com/assets/1143013/12315111/e7767c3e-ba77-11e5-8e71-e6c84a225196.png)

**Comment by davidmaack** [comment]
Is fixed in Version 2.0.0-alpha1 (https://github.com/menatwork/semantic_html5/releases/tag/2.0.0-alpha1)
