### ISSUE TITLE
Nur Gästen zeigen

### ISSUE THREAD

**Issue by chriza** [menatwork/semantic_html5#30]
Habe ein kleines Problem. Aktiviere ich "Nur Gästen zeigen" wird sich die Einstellung nur auf das öffnende Tag aber nicht auf das schließende Tag aus.

**Comment by davidmaack** [comment]
Fixed in https://github.com/menatwork/semantic_html5/commit/d08dd9d21f2a3ddb534d65177cb1804b1b5f0ddb
