### ISSUE TITLE
Creating infinite columns

### ISSUE THREAD

**Issue by dive13** [menatwork/semantic_html5#33]
Associated with [contao-bootstrap grid-editor](https://github.com/contao-bootstrap/grid-editor) (netzmacht creative) it would be very useful to allow infinite numbers of bootstrap colums to be created with semantic_html5.
Currently only the pre-defined numbers of columns in a row receive the bootstrap classes. So it is not possible to build a piece like this example in just one set of semantic_html5 containers: http://getbootstrap.com/examples/offcanvas/

**Comment by davidmaack** [comment]
Well isn't that an issue for https://github.com/contao-bootstrap/grid-editor? We only generate the HTML5-Element, anything associated with bootstrap is injected by the bootstrap extension.

@dmolineus: If you need any kind of Hook or adjustemts on semantic_html5 for this to work, I'm happy to help.

**Comment by dive13** [comment]
I dont´t know. The creator of the grid editor tells me that the grid editor supports this feature.
See: https://community.contao.org/de/showthread.php?61349-Spaltensets-und-semantic_html&p=423784&viewfull=1#post423784

**Comment by davidmaack** [comment]
Resolved by contao-bootstrap/grid-editor#15
